### ISSUE TITLE
Is pyvisa-py still active?  Can I/should I help?

### ISSUE THREAD

**Issue by unresto** [pyvisa/pyvisa-py#110]
I went looking for an NI-VISA alternative, but seem to be hitting similar usability issues to others with PipeError and other issues with Agilent/Keysight instruments over USB.

What the status of the pyvisa-py effort?  Is it actively being developed, should it continue (or not), and can I help if so?  Interest in getting both Windows and Linux supported and I have some time to contribute.

**Comment by MatthieuDartiailh** [comment]
The development is not very active because me and the other maintainers are quite busy (I alm defending my PhD in less than two weeks). Lastly I tried to focused on pyvisa but please feel free to contribute and I will make time to review your work.
I have little experience with direct USB, but you may want to take inspiration from python-usbtmc that appears to be better at handling corner cases. In addition there is a number of issues related to some encoding being called at the wrong time. There are multiple proposal to fix it but nobody took the time to actually checks it fix the real problem (on Python 2 and 3). If you have a little to look into it it would be great.
