### ISSUE TITLE
pyvisa in versioning wrong

### ISSUE THREAD

**Issue by mtsolmn** [pyvisa/pyvisa-py#266]
To Reproduce
--------------
1. `pip install pyvisa-py`
2. `pip check`
3. See error

pyvisa-py 0.0.0 has requirement pyvisa>1.10.1, but you have pyvisa 1.10.1.

This is because the install_requires dependency in setup.py has the versioning as 
```
install_requires =
    pyvisa>1.10.1
    ...
```

but it should be `pyvisa>=1.10.1`

I am aware that there is now version 1.11.0 released just last week, but seeing as this versioning in setup.py has not been changed in over a year, this has been a bug the entire time and only picked up now. Therefore, I think the above edit is still meant to be fixed.

**Comment by MatthieuDartiailh** [comment]
Thanks for your concern. At the time the version was bumped (last March) , it was not strictly necessary, however since the renaming of the installed package in #238 we need PyVISA >= 1.11. I have not started developing the next version but we will have a bugfix release relatively soon and I will update the version constraint then. I will close this issue when it is done.
